### ISSUE TITLE
un paquet opam serait super quand tu as une version stable

### ISSUE THREAD

**Issue by UnixJunkie** [tobast/OC4.5#1]

**Comment by tobast** [comment]
Actually, this is a project I've mostly let sit in a corner for some time now… To be packaged, I feel like it would require to have an active maintainer. IIRC, it was working pretty well last time I checked, though.

**Comment by UnixJunkie** [comment]
do you have a usage example of it?
IMHO, a stable and working piece of software is enough to be released.

**Comment by tobast** [comment]
I'll have to proof-read the code, this is quite old in my memory and I don't want to publish something without re-checking it.

I'm quite busy this week and the following, but if I forget to do that in some near-ish future, don't hesitate to remind me :)

**Comment by UnixJunkie** [comment]
I'd like to make a release soon, because I'd like to release of ORandForest too.
I have done extensive tests: performance is competitive with a linear SVM implementation.

**Comment by UnixJunkie** [comment]
underway here: https://github.com/ocaml/opam-repository/pull/11409

**Comment by UnixJunkie** [comment]
done
